// A texture is either a loaded image (PNG / SVG fetched by URL), a single noise
// field, or several noise fields composed over a base colour. `tileSize` is the
// world-unit size of one full repeat; smaller values tile more densely. For
// images, `size` controls SVG rasterisation resolution (ignored for raster).
export type ImageTextureSpec = {
  type: "image";
  url: string;
  size?: number;
  tileSize?: number;
};

export type NoiseTextureSpec = {
  type: "noise";
  algorithm: "perlin" | "fbm" | "worley";
  size?: number;       // canvas resolution (px), default 256
  scale?: number;      // noise frequency in tiles per texture
  colors?: [string, string]; // gradient endpoints, default ["#000","#fff"]
  seed?: number;
  tileSize?: number;
};

// Composed noise layers — useful for "messy" floors where one noise can't
// capture grain + stains + streaks at once. Each layer is rendered over the
// running buffer with the chosen blend mode and per-pixel opacity = noise * opacity.
export type LayeredNoiseTextureSpec = {
  type: "layered-noise";
  size?: number;
  tileSize?: number;
  baseColor: string;
  layers: Array<{
    algorithm: "perlin" | "fbm" | "worley";
    scale: number;
    seed?: number;
    color: string;
    blend?: "multiply" | "overlay" | "screen";
    opacity?: number; // 0–1, default 1
  }>;
};

// Tangent-space normal map generated by treating tileable noise as a height
// field and computing wrap-around Sobel gradients. Output is RGB-encoded
// normals in linear colour space. `strength` scales the height before the
// gradient so larger values give bumpier-looking surfaces.
export type NormalNoiseTextureSpec = {
  type: "normal-noise";
  algorithm: "perlin" | "fbm" | "worley";
  size?: number;
  scale?: number;
  seed?: number;
  strength?: number; // default 2
  tileSize?: number;
};

export type TextureSpec =
  | ImageTextureSpec
  | NoiseTextureSpec
  | LayeredNoiseTextureSpec;

export type NormalMapSpec = NormalNoiseTextureSpec;

// Fixture style used by CeilingLights / placeLights.
//   ceiling-pendant: warm hanging bulb under a small disc — original look
//   fluorescent:     cool rectangular ceiling panel — office building
//   explorer:        mix of warm corner-mounted spots and floor lanterns,
//                    placed irregularly as if dropped while exploring
export type LightStyle = "ceiling-pendant" | "fluorescent" | "explorer";

export interface LevelConfig {
  // Visuals
  wallColor: string;
  floorColor: string;
  ceilingColor: string;
  wallTexture?: TextureSpec;
  floorTexture?: TextureSpec;
  ceilingTexture?: TextureSpec;

  // Surface micro-detail. Normal maps add bumps revealed by grazing light;
  // roughness controls how matte/glossy the surface reads under that light.
  wallNormalMap?: NormalMapSpec;
  floorNormalMap?: NormalMapSpec;
  ceilingNormalMap?: NormalMapSpec;
  wallNormalScale?: number;     // default 1
  floorNormalScale?: number;    // default 1
  ceilingNormalScale?: number;  // default 1
  wallRoughness?: number;       // default 1 (fully matte)
  floorRoughness?: number;      // default 1
  ceilingRoughness?: number;    // default 1

  // Doors
  doorFrequency: number; // 0–1 probability per wall

  // Lighting
  ambientLight: number; // three.js ambient intensity
  lightSpacing: number; // base cell stride between lights (higher = fewer)
  lightStyle?: LightStyle; // default "ceiling-pendant"

  // Half-height partitions: walls the camera can see over but the player can't walk through
  halfHeightPartitions: boolean;
  halfHeightColor: string;
  halfHeightFrequency: number; // 0–1 probability that an eligible wall becomes half-height

  // Wider rooms: randomly remove internal walls post-generation so some areas open up
  widerRooms: boolean;
  widerRoomFrequency: number; // 0–1 probability that each internal wall is removed

  // Post-processing shader applied over the whole canvas, e.g. "vhs"
  shader?: string;
}

export const DEFAULT_LEVEL_CONFIG: LevelConfig = {
  wallColor: "#666666",
  floorColor: "#444444",
  ceilingColor: "#222222",
  doorFrequency: 0.1,
  ambientLight: 0.05,
  lightSpacing: 8,
  halfHeightPartitions: false,
  halfHeightColor: "#555555",
  halfHeightFrequency: 0.3,
  widerRooms: false,
  widerRoomFrequency: 0.2,
};
