// A texture is either a loaded image (PNG / SVG fetched by URL), a single noise
// field, or several noise fields composed over a base colour. `tileSize` is the
// world-unit size of one full repeat; smaller values tile more densely. For
// images, `size` controls SVG rasterisation resolution (ignored for raster).
export type ImageTextureSpec = {
  type: "image";
  url: string;
  size?: number;
  tileSize?: number;
};

// `scale` may be a single number or an [x, y] pair for anisotropic noise —
// e.g. [26, 4] varies fast horizontally and slowly vertically, reading as
// vertical stripes (wallpaper, wood grain). Worley ignores the y component.
export type NoiseScale = number | [number, number];

export type NoiseTextureSpec = {
  type: "noise";
  algorithm: "perlin" | "fbm" | "worley";
  size?: number;       // canvas resolution (px), default 256
  scale?: NoiseScale;  // noise frequency in tiles per texture
  colors?: [string, string]; // gradient endpoints, default ["#000","#fff"]
  seed?: number;
  tileSize?: number;
};

// Composed noise layers — useful for "messy" floors where one noise can't
// capture grain + stains + streaks at once. Each layer is rendered over the
// running buffer with the chosen blend mode and per-pixel opacity = noise * opacity.
export type LayeredNoiseTextureSpec = {
  type: "layered-noise";
  size?: number;
  tileSize?: number;
  baseColor: string;
  layers: Array<{
    algorithm: "perlin" | "fbm" | "worley";
    scale: NoiseScale;
    seed?: number;
    color: string;
    blend?: "multiply" | "overlay" | "screen";
    opacity?: number; // 0–1, default 1
    // Multiplies the layer's opacity by a vertical gradient: [top, bottom] of
    // the texture. On walls, one vertical repeat spans the full wall when
    // tileSize equals the wall height, so [0, 1] concentrates grime at the
    // floor and [1, 0] shades the ceiling line.
    verticalFade?: [number, number];
  }>;
};

// Tangent-space normal map generated by treating tileable noise as a height
// field and computing wrap-around Sobel gradients. Output is RGB-encoded
// normals in linear colour space. `strength` scales the height before the
// gradient so larger values give bumpier-looking surfaces.
export type NormalNoiseTextureSpec = {
  type: "normal-noise";
  algorithm: "perlin" | "fbm" | "worley";
  size?: number;
  scale?: NoiseScale;
  seed?: number;
  strength?: number; // default 2
  tileSize?: number;
};

// Regular grid of recessed lines over a flat base — suspended-ceiling tiles,
// linoleum, floorboards. `cells` lines per tile (override per axis with
// cellsX/cellsY; 0 disables that axis, so cellsX only = plank seams).
// Optional fbm mottling dirties the base; an anisotropic mottleScale
// stretches it into grain running along the boards.
export type GridTextureSpec = {
  type: "grid";
  size?: number;
  tileSize?: number;
  baseColor: string;
  lineColor: string;
  cells?: number;       // grid cells per tile, default 4
  cellsX?: number;      // vertical lines per tile, default `cells`
  cellsY?: number;      // horizontal lines per tile, default `cells`
  lineWidth?: number;   // line thickness in px, default 2
  mottle?: number;      // 0–1 fbm mottle opacity, default 0
  mottleColor?: string; // default a darker version of baseColor
  mottleScale?: NoiseScale; // default cells * 2
  seed?: number;
};

export type TextureSpec =
  | ImageTextureSpec
  | NoiseTextureSpec
  | LayeredNoiseTextureSpec
  | GridTextureSpec;

export type NormalMapSpec = NormalNoiseTextureSpec;

// Fixture style used by CeilingLights / placeLights.
//   ceiling-pendant: warm hanging bulb under a small disc — original look
//   fluorescent:     cool rectangular ceiling panel — office building
//   explorer:        mix of warm corner-mounted spots and floor lanterns,
//                    placed irregularly as if dropped while exploring
//   wall-sconce:     cold cylindrical fixtures mounted high on walls — dim
//                    residential hallway, pools of light on the wall below.
//                    Occasionally mixes in a flush ceiling drum variant, and
//                    falls back to it in cells with no wall to mount on.
export type LightStyle =
  | "ceiling-pendant"
  | "fluorescent"
  | "explorer"
  | "wall-sconce";

// Open-plan post-processing applied after maze generation: carve large
// clearings, thin the remaining walls out so isolated partition segments are
// left standing, and place freestanding columns at fully open junctions.
// Produces office/basement liminal space instead of corridors.
export interface OpenPlanConfig {
  clearings: number;             // number of large open areas to carve
  clearingSize: [number, number]; // clearing half-extent range, in cells
  wallRemoval: number;           // 0–1 chance each remaining interior wall is removed
  pillarFrequency: number;       // 0–1 chance an open junction hosts a column
  pillarSize?: number;           // column footprint in world units, default 0.5
}

export interface LevelConfig {
  // Visuals
  wallColor: string;
  floorColor: string;
  ceilingColor: string;
  // Room height in world units, default 3. Low values (~2.5) read as
  // office/basement space.
  wallHeight?: number;
  wallTexture?: TextureSpec;
  floorTexture?: TextureSpec;
  ceilingTexture?: TextureSpec;

  // Surface micro-detail. Normal maps add bumps revealed by grazing light;
  // roughness controls how matte/glossy the surface reads under that light.
  wallNormalMap?: NormalMapSpec;
  floorNormalMap?: NormalMapSpec;
  ceilingNormalMap?: NormalMapSpec;
  wallNormalScale?: number;     // default 1
  floorNormalScale?: number;    // default 1
  ceilingNormalScale?: number;  // default 1
  wallRoughness?: number;       // default 1 (fully matte)
  floorRoughness?: number;      // default 1
  ceilingRoughness?: number;    // default 1

  // Doors
  doorFrequency: number; // 0–1 probability per wall

  // Lighting
  // Player flashlight intensity multiplier, default 1. Set 0 for levels that
  // are fully lit — the beam hotspot looks wrong in bright space.
  flashlight?: number;
  ambientLight: number; // three.js ambient intensity
  lightSpacing: number; // base cell stride between lights (higher = fewer)
  lightStyle?: LightStyle; // default "ceiling-pendant"
  // Place lights on an exact stride grid (no jitter, no dead-end skipping) —
  // the relentless regularity of office fluorescents.
  lightGrid?: boolean;

  // Half-height partitions: walls the camera can see over but the player can't walk through
  halfHeightPartitions: boolean;
  halfHeightColor: string;
  halfHeightFrequency: number; // 0–1 probability that an eligible wall becomes half-height

  // Wider rooms: randomly remove internal walls post-generation so some areas open up
  widerRooms: boolean;
  widerRoomFrequency: number; // 0–1 probability that each internal wall is removed

  // Open-plan generation pass (see OpenPlanConfig). Supersedes widerRooms
  // when both are set: widerRooms runs first, then this.
  openPlan?: OpenPlanConfig;

  // Exponential-squared fog: distant corridors sink into `color` instead of
  // rendering crisply forever. Density ~0.05–0.1 for a cellSize-4 maze.
  fog?: { color: string; density: number };

  // Baseboard + crown moulding strips rendered along full-height walls.
  // `crown` defaults to true; set false for baseboard-only (drop ceilings).
  trim?: { color: string; roughness?: number; crown?: boolean };

  // Framed pictures hung on wall faces. `frequency` is the 0–1 probability
  // per face of each full-height plain wall (doors and half-walls are skipped).
  pictures?: { frequency: number; frameColor?: string };

  // Post-processing shader applied over the whole canvas, e.g. "vhs"
  shader?: string;
  // Per-level tuning knobs passed to the shader. Supported keys:
  //   film: grain (multiplier, default 1)
  //   vhs:  distortion (multiplier, default 1)
  shaderOptions?: Record<string, number>;
}

export const DEFAULT_LEVEL_CONFIG: LevelConfig = {
  wallColor: "#666666",
  floorColor: "#444444",
  ceilingColor: "#222222",
  doorFrequency: 0.1,
  ambientLight: 0.05,
  lightSpacing: 8,
  halfHeightPartitions: false,
  halfHeightColor: "#555555",
  halfHeightFrequency: 0.3,
  widerRooms: false,
  widerRoomFrequency: 0.2,
};
